Repository wouterboomsma/eigency, pull requests merged in 2022-02, with the labels that each got.

#27 Include .cpp files in MANIFEST.in
  MANIFEST.in
Labels: bug

#43 GitHub Actions
  .github/workflows/build.yml
  .github/workflows/setup.yml
  .github/workflows/wheel.yml
  .travis.yml
  README.md
  pyproject.toml
Labels: enhancement

#45 Fix MANIFEST.in
  MANIFEST.in
Labels: bug

#46 Make sdist tar file consistent across build environments
  .gitignore
  setup.cfg
Labels: bug

#47 Pre-release cleanup and linting
  .github/workflows/build.yml
  .github/workflows/pre-commit.yml
  .github/workflows/setup.yml
  .github/workflows/wheel.yml
  .pre-commit-config.yaml
  README.md
  eigency/__init__.py
  eigency/conversions.pxd
  eigency/conversions.pyx
  eigency/core.pxd
  eigency/core.pyx
  eigency/eigency_cpp.h
  pyproject.toml
  setup.cfg
  setup.py
  tests/eigency_tests/eigency_tests.pyx
  tests/run_tests.py
  tests/setup.py
Labels: cleanup
